version: '3.8'

services:
  cooldowns_db:
    image: redis:alpine
    restart: always
    networks:
      - redis-network
    ports:
      - "6379:6379"
  bot:
    build:
      context: bot
    restart: always
    depends_on:
      - cooldowns_db
    volumes:
      - ./logs/bot:/bot/src/logs
    environment:
      REDIS_URI: redis://cooldowns_db:6379
    networks:
      - redis-network
networks:
  redis-network:
