version: '3.8'

services:
    cooldowns_db:
        image: redis:alpine
        restart: always
        networks:
            - redis-network
        ports:
            - '6379:6379'
    bot:
        build:
            context: .
            dockerfile: ./docker/Bot.Dockerfile
        restart: always
        depends_on:
            - cooldowns_db
        environment:
            REDIS_URI: redis://cooldowns_db:6379
        networks:
            - redis-network
    support:
        build:
            context: .
            dockerfile: ./docker/Support.Dockerfile
        restart: always
    crons:
        build:
            context: .
            dockerfile: ./docker/Crons.Dockerfile
        restart: always
networks:
    redis-network:
