name: Lint and Build

on:
    push:
        branches:
            - main
            - development
    pull_request:
        branches:
            - main
            - development

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                project: [bot, crons, support]

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '21'

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 'latest'

            - name: Install Dependencies
              run: cd ${{ matrix.project }} && bun install --frozen-lockfile

            - name: Lint
              run: cd ${{ matrix.project }} && bun run lint
