name: CI

on:
    push:
        branches:
            - main
            - development
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        name: Build and Lint
        timeout-minutes: 5
        runs-on: ubuntu-latest
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
            AUTH_DISCORD_ID: ${{ secrets.AUTH_DISCORD_ID }}
            AUTH_DISCORD_SECRET: ${{ secrets.AUTH_DISCORD_SECRET }}
            LEMONSQUEEZY_API_KEY: ${{ secrets.LEMONSQUEEZY_API_KEY }}
            LEMONSQUEEZY_STORE_ID: ${{ secrets.LEMONSQUEEZY_STORE_ID }}
            LEMONSQUEEZY_WEBHOOK_SECRET: ${{ secrets.LEMONSQUEEZY_WEBHOOK_SECRET }}
            WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
            NODE_ENV: ${{ secrets.NODE_ENV }}
            NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}
        steps:
            - uses: actions/checkout@v4

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 'latest'

            - name: Install Dependencies
              run: bun install

            - name: Build
              run: bun run build

            - name: Lint
              run: bun run lint
