name: CI

on:
    push:
        branches:
            - main
            - development
    pull_request:
        types: [opened, synchronize]

jobs:
    build:
        name: Build and Lint
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '21'

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 'latest'

            - name: Install Dependencies
              run: bun install --frozen-lockfile

            - name: Build
              run: bun run build

            - name: Lint
              run: bun run lint
